# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hinge_start', models.BooleanField()),
                ('hinge_end', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField()),
                ('nature', models.IntegerField()),
                ('group', models.IntegerField()),
                ('f1', models.FloatField()),
                ('f2', models.FloatField()),
                ('coord1', models.FloatField()),
                ('coord2', models.FloatField()),
                ('m', models.FloatField()),
                ('deg', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('x_boundary_condition', models.BooleanField()),
                ('y_boundary_condition', models.BooleanField()),
                ('fi_boundary_condition', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('E', models.FloatField()),
                ('A', models.FloatField()),
                ('J', models.FloatField()),
                ('ro', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConcentratedLoad',
            fields=[
                ('load_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Load')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.load',),
        ),
        migrations.CreateModel(
            name='DistributedLoad',
            fields=[
                ('load_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Load')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.load',),
        ),
        migrations.CreateModel(
            name='DistributedXLoad',
            fields=[
                ('load_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Load')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.load',),
        ),
        migrations.AddField(
            model_name='load',
            name='associated_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Element'),
        ),
        migrations.AddField(
            model_name='load',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='element',
            name='node_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_end', to='app.Node'),
        ),
        migrations.AddField(
            model_name='element',
            name='node_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_start', to='app.Node'),
        ),
        migrations.AddField(
            model_name='element',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='element',
            unique_together=set([('node_start', 'node_end')]),
        ),
    ]
