# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='coord2',
        ),
        migrations.RemoveField(
            model_name='load',
            name='f2',
        ),
        migrations.RemoveField(
            model_name='load',
            name='group',
        ),
        migrations.RemoveField(
            model_name='load',
            name='nature',
        ),
    ]
