# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_load_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set([('x', 'y')]),
        ),
    ]
