# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170723_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='load',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='node',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='project_name',
        ),
    ]
