# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171209_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='end_x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='end_y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='start_x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='start_y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
