# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171209_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='end_x',
        ),
        migrations.RemoveField(
            model_name='element',
            name='end_y',
        ),
        migrations.RemoveField(
            model_name='element',
            name='start_x',
        ),
        migrations.RemoveField(
            model_name='element',
            name='start_y',
        ),
    ]
