# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('E', models.FloatField()),
                ('A', models.FloatField()),
                ('J', models.FloatField()),
                ('ro', models.FloatField()),
                ('node_start', models.IntegerField()),
                ('node_end', models.IntegerField()),
                ('hinge_start', models.BooleanField()),
                ('hinge_end', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('x_boundary_condition', models.BooleanField()),
                ('y_boundary_condition', models.BooleanField()),
                ('fi_boundary_condition', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
