# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('E', models.FloatField()),
                ('A', models.FloatField()),
                ('J', models.FloatField()),
                ('ro', models.FloatField()),
                ('hinge_start', models.BooleanField()),
                ('hinge_end', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('x_boundary_condition', models.BooleanField()),
                ('y_boundary_condition', models.BooleanField()),
                ('fi_boundary_condition', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='element',
            name='node_end',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_end', to='app.Node'),
        ),
        migrations.AddField(
            model_name='element',
            name='node_start',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_start', to='app.Node'),
        ),
    ]
