# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170708_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='node_end',
        ),
        migrations.AddField(
            model_name='element',
            name='node_end',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='node_end', to='app.Node'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='element',
            name='node_start',
        ),
        migrations.AddField(
            model_name='element',
            name='node_start',
            field=models.OneToOneField(default='sa', on_delete=django.db.models.deletion.CASCADE, related_name='node_start', to='app.Node'),
            preserve_default=False,
        ),
    ]
